In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# /content/drive/MyDrive/TVS/Task0-CAD-to-Graph/v8-engine-block-3d-model-1.snapshot.4/Camshaft_Cap.STEP

In [6]:
! pip install pyvista cascadio -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 28.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 53.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.5/213.5 kB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 6.7 MB/s eta 0:00:00


In [7]:
# import cascadio
import pyvista as pv

If we have object in other format that doesn't supported by PyVista, then first convert to PyVista supported format.
i.e: here .STEP -> .stl

In [8]:
step_file_path = '/content/drive/MyDrive/TVS/Task0-CAD-to-Graph/v8-engine-block-3d-model-1.snapshot.4/Camshaft_Cap.STEP'
output_obj_path = '/content/drive/MyDrive/TVS/Task0-CAD-to-Graph/Camshaft_Cap.obj' # Intermediate OBJ file
output_stl_path = '/content/drive/MyDrive/TVS/Task0-CAD-to-Graph/Camshaft_Cap.stl'

# Convert STEP to OBJ using cascadio
cascadio.step_to_obj(step_file_path, output_obj_path)
print(f"Successfully converted '{step_file_path}' to '{output_obj_path}'")

# Load the OBJ file with PyVista and save as STL
mesh = pv.read(output_obj_path)
mesh.save(output_stl_path)

print(f"Successfully converted '{output_obj_path}' to '{output_stl_path}'")

NameError: name 'cascadio' is not defined



---



In [9]:
!pip install pyvista vtk -q

In [10]:
!pip install "pyvista[jupyter]"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.7/250.7 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 831.8/831.8 kB 13.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 21.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.1/45.1 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 26.8 MB/s eta 0:00:00


In [57]:
import pyvista as pv
pv.set_jupyter_backend('html')

# Camshaft_Cap
stl_obj_path = "/content/drive/MyDrive/TVS/Task0-CAD-to-Graph/Camshaft_Cap.stl"
# stl_obj_path = "/content/drive/MyDrive/TVS/Task0-CAD-to-Graph/Blade_Type_5.stl"
mesh = pv.read(stl_obj_path)
mesh.plot()

EmbeddableWidget(value='<iframe srcdoc="<!doctype html>\n<html lang=&quot;en&quot;>\n  <head>\n    <meta chars…

In [58]:
# The .stl object used here contains surface data only.
# But if object contains volume data and we want to extract surface data then
# following line of code is used:-
surface_mesh = mesh.extract_surface(algorithm='dataset_surface')

In [59]:
print("Number of points in given object:", mesh.n_points)
print("Number of cells in given object:", mesh.n_cells)

Number of points in given object: 4020
Number of cells in given object: 8036


In [60]:
mesh_points = mesh.points
print("mesh_points: ",mesh_points)

mesh_points:  [[  1.38874    0.        19.987465]
 [  1.5        0.        20.      ]
 [  1.5       -0.884667  19.980425]
 ...
 [  1.049516   0.884597 -19.697088]
 [  1.012536   0.879856 -19.591513]
 [  1.         0.874864 -19.480364]]


In [61]:
mesh_faces = mesh.faces
print("mesh faces in compact '3, p1v1, p1v2, p1v3, ...' form:",mesh_faces)

mesh_faces = mesh_faces.reshape(-1,4)[:, 1:]
print("mesh faces in original '(v1, v2, v3)' form:",mesh_faces)

mesh faces in compact '3, p1v1, p1v2, p1v3, ...' form: [   3    0    1 ... 3455 3481 3468]
mesh faces in original '(v1, v2, v3)' form: [[   0    1    2]
 [   3    4    5]
 [   3    6    4]
 ...
 [3455 3437 3481]
 [3455 3444 3437]
 [3455 3481 3468]]


#Create edges

In [62]:
# THIS CODE MIGHT ADD REDUNDANT EDGES. i.e: 1-2 AND 2-1
# edges = []
# for tri in mesh_faces:
#   a, b, c = tri
#   edges.extend([
#       [a, b],
#       [b, c],
#       [c, a]
#   ])

# print(type(edges))
# print(edges)

In [63]:
# BY USING SORTED TUPLE, REDUNDANCY IS AVOIDED
edges = set()

for tri in mesh_faces:
    a, b, c = tri

    edges.update([
        tuple(sorted((a, b))),
        tuple(sorted((b, c))),
        tuple(sorted((c, a)))
    ])

print(edges)

{(np.int64(266), np.int64(268)), (np.int64(947), np.int64(1649)), (np.int64(3858), np.int64(3865)), (np.int64(250), np.int64(260)), (np.int64(1876), np.int64(1883)), (np.int64(2736), np.int64(2741)), (np.int64(2156), np.int64(2166)), (np.int64(2367), np.int64(2386)), (np.int64(3640), np.int64(3642)), (np.int64(1059), np.int64(1072)), (np.int64(2499), np.int64(2505)), (np.int64(1979), np.int64(1981)), (np.int64(2029), np.int64(2098)), (np.int64(3589), np.int64(3596)), (np.int64(3009), np.int64(3021)), (np.int64(2429), np.int64(2446)), (np.int64(41), np.int64(42)), (np.int64(3633), np.int64(3639)), (np.int64(1632), np.int64(1644)), (np.int64(904), np.int64(905)), (np.int64(324), np.int64(330)), (np.int64(2511), np.int64(2515)), (np.int64(2772), np.int64(2785)), (np.int64(2791), np.int64(2798)), (np.int64(1395), np.int64(1408)), (np.int64(3415), np.int64(3416)), (np.int64(2255), np.int64(2266)), (np.int64(839), np.int64(3176)), (np.int64(2047), np.int64(3054)), (np.int64(3296), np.int64(3

#Create adjacency matrix

In [64]:
import numpy as np
num_nodes = mesh.n_points

adj_matrix = np.zeros((num_nodes, num_nodes), dtype=int)

for u, v in edges:
    adj_matrix[u][v] = 1
    adj_matrix[v][u] = 1

print(adj_matrix)

[[0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 1 0]]


#Create edge_index


In [ ]:
edge_index = np.array(list(edges)).T
# [0] => source nodes, [1] => destinaiton nodes
print(edge_index) 
print(edge_index.shape)

[[ 266  947 3858 ... 3796 3534 2374]
 [ 268 1649 3865 ... 3805 3539 2389]]
(2, 12054)


#Extract norms data. Norm => direction of surface

In [66]:
mesh_with_normals = mesh.compute_normals(
    cell_normals=False,
    point_normals=True
)

normals = mesh_with_normals.point_data['Normals']

print(normals)
print(normals.shape)

[[ 2.2292241e-01  2.8627517e-04 -9.7483617e-01]
 [ 6.7276411e-02 -4.4043968e-03 -9.9772465e-01]
 [ 5.6072626e-02  3.6860384e-02 -9.9774605e-01]
 ...
 [ 8.9387077e-01 -2.1178359e-02  4.4782427e-01]
 [ 9.7838235e-01 -8.2137799e-03  2.0664100e-01]
 [ 9.9930137e-01 -1.6767461e-03  3.7335921e-02]]
(4020, 3)


#Finally, create features-list [[x_coord, y_coord, z_coord, x_norm, y_norm, z_norm]]

In [67]:
coords = mesh.points
normals = mesh_with_normals.point_data['Normals']

node_features = np.hstack([coords, normals])

print(node_features)
print(node_features.shape)

[[ 1.3887399e+00  0.0000000e+00  1.9987465e+01  2.2292241e-01
   2.8627517e-04 -9.7483617e-01]
 [ 1.5000000e+00  0.0000000e+00  2.0000000e+01  6.7276411e-02
  -4.4043968e-03 -9.9772465e-01]
 [ 1.5000000e+00 -8.8466698e-01  1.9980425e+01  5.6072626e-02
   3.6860384e-02 -9.9774605e-01]
 ...
 [ 1.0495160e+00  8.8459700e-01 -1.9697088e+01  8.9387077e-01
  -2.1178359e-02  4.4782427e-01]
 [ 1.0125360e+00  8.7985599e-01 -1.9591513e+01  9.7838235e-01
  -8.2137799e-03  2.0664100e-01]
 [ 1.0000000e+00  8.7486398e-01 -1.9480364e+01  9.9930137e-01
  -1.6767461e-03  3.7335921e-02]]
(4020, 6)


#Compare graph with mesh-structure

In [68]:
# convert edges into PyVista line format
lines = []

for u, v in edges:
    lines.extend([2, u, v])

lines = np.array(lines)

# create graph mesh
graph = pv.PolyData()
graph.points = mesh_points
graph.lines = lines

# interactive plot
plotter = pv.Plotter(notebook=True)

# actual mesh
plotter.add_mesh(
    mesh,
    color='lightblue',
    opacity=0.4,
    show_edges=False,
    label = "original mesh"
)

# graph edges
plotter.add_mesh(
    graph,
    color='red',
    line_width=1,
    label = "graph edges"
)

# graph nodes
plotter.add_points(
    mesh_points,
    color='black',
    point_size=5,
    label = "graph points/nodes/vertices",
    render_points_as_spheres=True
)

plotter.add_legend()


# plotter.show(jupyter_backend='html')

<vtkmodules.vtkRenderingAnnotation.vtkLegendBoxActor(0x41f37ca0) at 0x7afcc69d23e0>

#Create data appropriate for torch_geometric

In [69]:
!pip install torch_geometric -q

In [70]:
from torch_geometric.data import Data
import torch

edge_index = torch.tensor(list(edges), dtype=torch.long).t().contiguous()

data = Data(
    x=torch.tensor(node_features, dtype=torch.float),
    edge_index=edge_index
)

print("data: ", data)

data:  Data(x=[4020, 6], edge_index=[2, 12054])


In [71]:
# extract points from pyG-GRAPH
pyG_points = data.x[:, :3].numpy()
print("pyG_points.shape: ", pyG_points.shape)

# extract candidate-edges-idx from pyG-GRAPH
pyG_edge_idx = data.edge_index.numpy() # sourse-destination format yet
print("pyG_edge_idx", pyG_edge_idx.shape)


pyG_points.shape:  (4020, 3)
pyG_edge_idx (2, 12054)


In [72]:
# create actual edges from sourse-destinaiton edge-list
pyG_edges = []

for idx in range(len(pyG_edge_idx[0])):
  v = pyG_edge_idx[0][idx]
  u = pyG_edge_idx[1][idx]
  pyG_edges.extend([2, v, u])

pyG_edges = np.array(pyG_edges)
pyG_edges[:5]
# 2, n1, n2, 2, n3, n4, ...
# 3,n1,n2,n3, 3,n4,n5,n6, ...

array([  2, 266, 268,   2, 947])

In [73]:
recreated_pvGraph = pv.PolyData()
recreated_pvGraph.points = pyG_points
recreated_pvGraph.lines = pyG_edges

plotter = pv.Plotter(notebook=True)

plotter.add_mesh(
    mesh,
    color='lightblue',
    opacity=0.35,
    label='Original Mesh'
)

plotter.add_mesh(
    recreated_pvGraph,
    color='red',
    line_width=1,
    label='Graph Edges'
)

plotter.add_points(
    recreated_pvGraph.points,
    color='black',
    line_width=1,
    label='Graph Points'
)

plotter.add_axes()

plotter.show(jupyter_backend='html')

EmbeddableWidget(value='<iframe srcdoc="<!doctype html>\n<html lang=&quot;en&quot;>\n  <head>\n    <meta chars…

#Create .vtm file

In [74]:
# ALL CODE TOGATHER

import pyvista as pv
import numpy as np

# 1. LOAD STL FILE
pv.set_jupyter_backend('html')
stl_obj_path = "/content/drive/MyDrive/TVS/Task0-CAD-to-Graph/Blade_Type_5.stl"
mesh = pv.read(stl_obj_path)

print("Number of points:", mesh.n_points)
print("Number of cells:", mesh.n_cells)
# ---------------------------------------------------


# 2. EXTRACT POINTS (VERTICES)
points = mesh.points
print("Points shape:", points.shape)
# ---------------------------------------------------


# 3. EXTRACT FACES
faces = mesh.faces

# Convert compact form:
# [3, v1, v2, v3, 3, v1, v2, v3 ...]
# into:
# [[v1,v2,v3],
#  [v1,v2,v3]]

faces = faces.reshape(-1, 4)[:, 1:]

print("Faces shape:", faces.shape)
# ---------------------------------------------------


# 4. CREATE GRAPH EDGES
edges = set()

for tri in faces:
    a, b, c = tri

    edges.update([
        tuple(sorted((a, b))),
        tuple(sorted((b, c))),
        tuple(sorted((c, a)))
    ])

print("Number of unique edges:", len(edges))
# ---------------------------------------------------


# 5. COMPUTE SURFACE NORMALS
mesh_with_normals = mesh.compute_normals(
    cell_normals=False,
    point_normals=True
)

normals = mesh_with_normals.point_data['Normals']
print("Normals shape:", normals.shape)
# ---------------------------------------------------


# 6. CREATE NODE FEATURES

# Features:
# [x, y, z, nx, ny, nz]

node_features = np.hstack([points, normals])
print("Node feature shape:", node_features.shape)
print("\nSample node feature:")
print(node_features[0])
# ---------------------------------------------------



# 7. CREATE GRAPH POLYDATA

# PyVista line format:
# [2, p1, p2, 2, p1, p2 ...]

lines = []

for u, v in edges:
    lines.extend([2, u, v])

lines = np.array(lines)

graph = pv.PolyData()
graph.points = points
graph.lines = lines
# ---------------------------------------------------



# 8. ADD FEATURES TO MESH
mesh.point_data['Normals'] = normals
mesh.point_data['NodeFeatures'] = node_features
# ---------------------------------------------------



# 9. CREATE MULTIBLOCK DATASET
multi = pv.MultiBlock()
multi['mesh'] = mesh
multi['graph'] = graph
# ---------------------------------------------------


# 10. SAVE AS .VTM
vtm_output_path = "/content/drive/MyDrive/TVS/Task0-CAD-to-Graph/cad_graph.vtm"
multi.save(vtm_output_path)
print(f"\nSaved .vtm file at: {vtm_output_path}")
# ---------------------------------------------------



# 11. INTERACTIVE VISUALIZATION
plotter = pv.Plotter(notebook=True)

# original mesh
plotter.add_mesh(
    mesh,
    color='lightblue',
    opacity=0.4
)

# graph edges
plotter.add_mesh(
    multi['mesh'],
    color='red',
    line_width=1
)

# graph nodes
plotter.add_points(
    points,
    color='black',
    point_size=5,
    render_points_as_spheres=True
)

plotter.show(jupyter_backend='html')

Number of points: 3297
Number of cells: 6610
Points shape: (3297, 3)
Faces shape: (6610, 3)
Number of unique edges: 9915
Normals shape: (3297, 3)
Node feature shape: (3297, 6)

Sample node feature:
[-20.579075     3.4162598    0.           0.7007493   -0.08778591
  -0.707986  ]

Saved .vtm file at: /content/drive/MyDrive/TVS/Task0-CAD-to-Graph/cad_graph.vtm


EmbeddableWidget(value='<iframe srcdoc="<!doctype html>\n<html lang=&quot;en&quot;>\n  <head>\n    <meta chars…